# Generated by Django 2.2.1 on 2019-07-03 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20190630_1616'),
        ('users', '0002_auto_20190630_1412'),
    ]

    operations = [
    ]
