# Generated by Django 2.2.1 on 2019-06-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(verbose_name='作品编号')),
                ('work_type', models.IntegerField(choices=[(1, '科技发明制作'), (2, '调查报告和学术论文')], verbose_name='大类类别')),
                ('title', models.CharField(max_length=255, verbose_name='作品名称')),
                ('department', models.CharField(max_length=255, verbose_name='院系名称')),
                ('field', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], verbose_name='专业领域')),
                ('detail', models.TextField(verbose_name='作品总体情况说明')),
                ('innovation', models.TextField(verbose_name='创新点')),
                ('keywords', models.CharField(max_length=255, verbose_name='关键词')),
                ('check_status', models.BooleanField(default=False, verbose_name='初审结果')),
                ('avg_score', models.FloatField(verbose_name='平均分')),
                ('if_defense', models.BooleanField(default=False, verbose_name='是否答辩')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.CompetitionRegistration', verbose_name='参赛记录')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('appendix_type', models.IntegerField(choices=[(1, '文档'), (2, '图片'), (3, '视频')], verbose_name='文件类型')),
                ('upload_date', models.DateField(verbose_name='上传日期')),
                ('file', models.FileField(upload_to='techwork/', verbose_name='文件')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techworks.WorkInfo', verbose_name='作品')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
            },
        ),
    ]
