# Generated by Django 2.2.2 on 2019-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinfo',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='是否已提交'),
        ),
    ]
