# Generated by Django 2.2.1 on 2019-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('techworks', '0002_workinfo_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinfo',
            name='labels',
            field=models.CharField(default='{"labels":[]}', max_length=255, verbose_name='作品标签'),
        ),
    ]
