# Generated by Django 2.2.1 on 2019-07-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('techworks', '0003_workinfo_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinfo',
            name='review_status',
            field=models.BooleanField(default=False, verbose_name='是否评价完毕'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='check_status',
            field=models.IntegerField(choices=[(-1, '未初审'), (1, '初审通过'), (0, '初审未通过')], default=-1,
                                      verbose_name='初审结果'),
        ),
    ]
