# Generated by Django 2.2.1 on 2019-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评审意见')),
                ('add_time', models.DateField(verbose_name='邀请时间')),
                ('review_status', models.IntegerField(choices=[(0, '未接受'), (1, '已接收'), (2, '已评价')], verbose_name='评价状态')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
            },
        ),
    ]
