# Generated by Django 2.2.1 on 2019-06-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('users', '0001_initial'),
        ('techworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Expert', verbose_name='专家'),
        ),
        migrations.AddField(
            model_name='review',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techworks.WorkInfo', verbose_name='作品'),
        ),
    ]
