# Generated by Django 2.2.1 on 2019-07-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('operation', '0002_auto_20190629_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.IntegerField(choices=[(0, '邮件已发出'), (1, '专家已拒绝'), (2, '专家尚未评价'), (3, '评价已暂存'), (4, '评价已提交')],
                                      verbose_name='评价状态'),
        ),
    ]
