# Generated by Django 2.2.1 on 2019-06-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='竞赛标题')),
                ('abstract', models.TextField(verbose_name='竞赛摘要')),
                ('detail', models.TextField(verbose_name='竞赛详细信息')),
                ('rule', models.TextField(verbose_name='竞赛规则')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '报名阶段'), (2, '初审阶段'), (3, '初评阶段'), (4, '现场答辩阶段'), (5, '已结束')], verbose_name='竞赛状态')),
                ('init_date', models.DateField(verbose_name='竞赛开始时间')),
                ('submit_end_date', models.DateField(verbose_name='提交截止时间')),
                ('check_end_date', models.DateField(verbose_name='初审截止时间')),
                ('review_end_date', models.DateField(verbose_name='初评截止时间')),
                ('defense_end_date', models.DateField(verbose_name='现场答辩结束时间')),
                ('finish_date', models.DateField(verbose_name='竞赛终止时间')),
                ('preview_img', models.ImageField(upload_to='competition/img/', verbose_name='预览图')),
                ('detail_img', models.ImageField(upload_to='competition/img/', verbose_name='详情图')),
                ('result_details', models.TextField(verbose_name='比赛结果详情')),
                ('start_appendix', models.FileField(upload_to='competition/appendix/', verbose_name='比赛公告附件')),
                ('end_appendix', models.FileField(upload_to='competition/appendix/', verbose_name='比赛结果附件')),
            ],
            options={
                'verbose_name': '科技竞赛',
                'verbose_name_plural': '科技竞赛',
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition', verbose_name='竞赛')),
            ],
            options={
                'verbose_name': '竞赛注册',
                'verbose_name_plural': '竞赛注册',
            },
        ),
    ]
