# Generated by Django 2.2.1 on 2019-06-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='fifth_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Student', verbose_name='第五作者'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='first_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Student', verbose_name='第一作者'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='forth_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Student', verbose_name='第四作者'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='second_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Student', verbose_name='第二作者'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='third_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Student', verbose_name='第三作者'),
        ),
    ]
